server:
  port: 8023

spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  shardingsphere:
    props:
      sql:
        show:
          true
    datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/acme?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: biosan#17
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://172.17.90.226:3306/acme?serverTimezone=Asia/Shanghai&useSSL=false
        username: root
        password: biosan#17
#    sharding:
#      defaultDatabaseStrategy:
#        complex:
#          algorithm-class-name: cn.eassen.mydynamicdatasource.shardingsphere.MyComplexDatasourceRoutingAlgorithm
#          sharding-columns: centerid, center_id, centerId
#
#      defaultTableStrategy:
#        none:
#          any: ""

mybatis:
  mapper-locations: classpath:mapper/**/*.xml